/**
 * Canonical stat ID registry.
 * Every stat in the engine is identified by one of these string literals.
 */
export const STAT_IDS = [
  // Primary attributes
  "strength",
  "dexterity",
  "intelligence",
  "vitality",
  "attunement",

  // Core offense
  "damage",
  "melee_damage",
  "spell_damage",
  "throwing_damage",
  "minion_damage",
  "hit_damage",
  "damage_over_time",
  "physical_damage",
  "attack_speed",
  "cast_speed",
  "cast_speed_per_2_intelligence",
  "crit_chance",
  "base_crit_chance",
  "crit_multiplier",
  "added_melee_physical_damage",
  "added_spell_fire_damage",
  "added_spell_cold_damage",
  "added_spell_lightning_damage",
  "added_spell_damage",
  "increased_damage",
  "increased_elemental_damage",
  "increased_fire_damage",
  "increased_cold_damage",
  "increased_lightning_damage",
  "increased_spell_damage",
  "increased_physical_damage",
  "increased_melee_damage",
  "increased_throwing_damage",
  "increased_necrotic_damage",
  "increased_void_damage",
  "increased_poison_damage",
  "increased_minion_damage",
  "more_damage",
  "more_melee_damage",
  "penetration_fire",
  "penetration_cold",
  "penetration_lightning",
  "penetration_elemental",
  "penetration_physical",
  "penetration_necrotic",
  "penetration_void",
  "ailment_chance",
  "ignite_chance",
  "shock_chance",
  "chill_chance",
  "bleed_chance",
  "poison_chance",
  "freeze_rate",
  "freeze_rate_multiplier",
  "stun_chance",
  "slow_chance",
  "armor_shred_chance",

  // Conditional damage (vs ailment)
  "hit_damage_against_shocked_enemies",
  "hit_damage_against_chilled_enemies",
  "hit_damage_against_ignited_enemies",
  "hit_damage_against_poisoned_enemies",
  "hit_damage_against_bleeding_enemies",
  "hit_damage_against_slowed_enemies",
  "hit_damage_against_stunned_enemies",
  "hit_damage_at_full_health",
  "hit_damage_with_ward",
  "damage_to_shocked",
  "damage_to_chilled",
  "damage_to_ignited",
  "damage_to_poisoned",
  "damage_to_bleeding",
  "damage_to_slowed",
  "damage_to_stunned",
  "damage_to_bosses",
  "more_damage_against_shocked",
  "more_damage_against_chilled",
  "more_damage_against_ignited",
  "more_damage_against_poisoned",
  "more_damage_against_bleeding",
  "more_damage_against_slowed",
  "more_damage_against_stunned",
  "more_damage_against_bosses",
  "lightning_damage_to_shocked_enemies",
  "spell_damage_to_shocked_enemies",

  // Core defense
  "health",
  "ward",
  "ward_gained",
  "armor",
  "dodge_rating",
  "block_chance",
  "block_effectiveness",
  "endurance",
  "endurance_threshold",
  "fire_resistance",
  "cold_resistance",
  "lightning_resistance",
  "necrotic_resistance",
  "void_resistance",
  "poison_resistance",
  "physical_resistance",
  "less_damage_taken",
  "glancing_blow_chance",

  // Sustain & utility
  "mana",
  "mana_cost",
  "mana_efficiency",
  "mana_gain",
  "mana_regen",
  "health_regen",
  "health_leech",
  "ward_generation",
  "ward_retention",
  "cooldown_recovery_speed",
  "movement_speed",
  "area",

  // Derived / composite (computed by calc engine)
  "effective_health",
  "average_hit",
  "expected_dps",
  "minion_average_hit_estimate",
  "minion_dps_estimate",
  "ignite_dps_estimate",
  "bleed_dps_estimate",
  "poison_dps_estimate",
  "ailment_dps_estimate",
  "health_leech_per_second",
  "ward_per_second",
  "armor_damage_reduction",
  "dodge_chance",
  "block_damage_reduction",
  "glancing_blow_damage_reduction",
  "total_less_damage_taken",
] as const;

export type StatId = (typeof STAT_IDS)[number];

/** Set for fast lookup */
export const STAT_ID_SET: ReadonlySet<string> = new Set(STAT_IDS);
